### ISSUE TITLE
support for PDEP and PEXT instructions

### ISSUE THREAD

**Issue by jayfoad** [StanfordPL/stoke-release#17]
This is a feature request: it would be great if STOKE supported the BMI2 instructions PDEP and PEXT.

**Comment by eschkufz** [comment]
STOKE should currently support these. Are you trying to do something and running into a bug?

**Comment by bchurchill** [comment]
Are you looking for validator support or sandbox support?


Berkeley

<div>-------- Original message --------</div><div>From: jayfoad <notifications@github.com> </div><div>Date:02/11/2015  07:27  (GMT-08:00) </div><div>To: eschkufz/stoke-release <stoke-release@noreply.github.com> </div><div>Cc:  </div><div>Subject: [stoke-release] support for PDEP and PEXT instructions (#17) </div><div>
</div>This is a feature request: it would be great if STOKE supported the BMI2 instructions PDEP and PEXT.

**Comment by jayfoad** [comment]
I'm trying to run stoke extract on an object file that contains pdep instructions and getting:
```
$ stoke extract -i bmi2.o -o bins2Error on line 6: Unable to parse instruction!
Error on line 7: Unable to parse instruction!
Error on line 10: Unable to parse instruction!
Error on line 12: Unable to parse instruction!
Error on line 15: Unable to parse instruction!
Error on line 17: Unable to parse instruction!
Error on line 11: Unable to parse instruction!
```
I'm guessing the line numbers refer to the generated .s file in the bins2/ directory:
```
$ cat bins2/bmi2_transpose_word.s 
  .text
  .globl bmi2_transpose_word
  .type bmi2_transpose_word, @function
.bmi2_transpose_word:                   
  movq %rdi, %rdx                 # 0   
  movq $0x5555555555555555, %rsi  # 1   
  movq $0xaaaaaaaaaaaaaaaa, %rax  # 2   
  shrq $0x20, %rdx                # 3   
  adcw %xmm0, %xmm0               # 4   
  adcw %xmm0, %xmm0               # 5   
  orq %rdx, %rcx                  # 6   
  movq %rcx, %rdx                 # 7   
  adcw %xmm0, %xmm0               # 8   
  shrq $0x20, %rdx                # 9   
  adcw %xmm0, %xmm0               # 10  
  orq %rdx, %rdi                  # 11  
  movq %rdi, %rdx                 # 12  
  adcw %xmm0, %xmm0               # 13  
  shrq $0x20, %rdx                # 14  
  adcw %xmm0, %xmm0               # 15  
...
```
And the first problem I noticed in this .s file is that my pdep instructions seem to have been disassembled as "adcw". Here's the output of objdump -d for comparison:
```
$ objdump -d bmi2.o

bmi2.o:     file format elf64-x86-64


Disassembly of section .text:

0000000000000000 <bmi2_transpose_word>:
   0:	48 89 fa             	mov    %rdi,%rdx
   3:	48 be 55 55 55 55 55 	movabs $0x5555555555555555,%rsi
   a:	55 55 55 
   d:	48 b8 aa aa aa aa aa 	movabs $0xaaaaaaaaaaaaaaaa,%rax
  14:	aa aa aa 
  17:	48 c1 ea 20          	shr    $0x20,%rdx
  1b:	c4 e2 c3 f5 ce       	pdep   %rsi,%rdi,%rcx
  20:	c4 e2 eb f5 d0       	pdep   %rax,%rdx,%rdx
  25:	48 09 d1             	or     %rdx,%rcx
  28:	48 89 ca             	mov    %rcx,%rdx
  2b:	c4 e2 f3 f5 fe       	pdep   %rsi,%rcx,%rdi
  30:	48 c1 ea 20          	shr    $0x20,%rdx
  34:	c4 e2 eb f5 d0       	pdep   %rax,%rdx,%rdx
  39:	48 09 d7             	or     %rdx,%rdi
  3c:	48 89 fa             	mov    %rdi,%rdx
  3f:	c4 e2 c3 f5 fe       	pdep   %rsi,%rdi,%rdi
  44:	48 c1 ea 20          	shr    $0x20,%rdx
  48:	c4 e2 eb f5 c0       	pdep   %rax,%rdx,%rax
  4d:	48 09 f8             	or     %rdi,%rax
...
```

**Comment by eschkufz** [comment]
This looks like a bug in the x64asm library that stoke depends on.

The x64asm parser thinks that the 64-bit variant of pdep uses the
pdelq mnemonic.
I'll file a bug report against x64asm and let you know when its fixed. Once
it is, a fresh checkout of stoke should work with this code.

**Comment by eschkufz** [comment]
Can you try either doing a fresh checkout or a make dist_clean; make?

I think the bug should be fixed now.

**Comment by jayfoad** [comment]
The stoke-release Makefile currently checks out a specific version of x64asm, which doesn't include the fix. If I change it to check out the "develop" branch then everything works. Thanks!

**Comment by bchurchill** [comment]
We need to update that.  This will introduce some bugs, particularly
relating to search.  I think if you run 'make test' inside stoke it will
show some errors.

**Comment by eschkufz** [comment]
I'll take care of that.

**Comment by bchurchill** [comment]
This is (hopefully) fixed in the new stoke release which includes the latest x64asm.  Here's a link to that: https://github.com/StanfordPL/stoke

If there's still an issue here, please open a ticket in the new repository.
