### ISSUE TITLE
stroke extract error

### ISSUE THREAD

**Issue by zefyrr** [StanfordPL/stoke-release#20]
When I try to do 

stoke extract -i ./a.out -o bins

I keep getting -

Error on line 0: syntax error, unexpected LABEL, expecting COLON

Any advice?

**Comment by bchurchill** [comment]
Can you double-check that you have objdump installed?  Try running 'objdump -d a.out' on the command line and make sure it dumps out some content.

Assuming that's all OK -- stoke extract works by parsing objdump's output, and it's possible you've hit a corner case.  Could you send us your a.out binary somehow?  You can email it to me at berkeley@berkeleychurchill.com if you like.

**Comment by tterribe** [comment]
Not the original reporter, but I've hit the same issue. I'll e-mail you the binary.

Here is the output of objdump -d on it (note that the first line is blank, but this is also true on a different binary where extract works):

bins/divpow2re:     file format elf64-x86-64


Disassembly of section .init:

0000000000400420 <_init>:
  400420:       48 83 ec 08             sub    $0x8,%rsp
  400424:       48 8b 05 b5 0b 20 00    mov    0x200bb5(%rip),%rax        # 600fe0 <_DYNAMIC+0x1e0>
  40042b:       48 85 c0                test   %rax,%rax
  40042e:       74 05                   je     400435 <_init+0x15>
  400430:       e8 2b 00 00 00          callq  400460 <__gmon_start__@plt>
  400435:       48 83 c4 08             add    $0x8,%rsp
  400439:       c3                      retq   

Disassembly of section .plt:

0000000000400440 <__libc_start_main@plt-0x10>:
  400440:       ff 35 aa 0b 20 00       pushq  0x200baa(%rip)        # 600ff0 <_GLOBAL_OFFSET_TABLE_+0x8>
  400446:       ff 25 ac 0b 20 00       jmpq   *0x200bac(%rip)        # 600ff8 <_GLOBAL_OFFSET_TABLE_+0x10>
  40044c:       0f 1f 40 00             nopl   0x0(%rax)

0000000000400450 <__libc_start_main@plt>:
  400450:       ff 25 aa 0b 20 00       jmpq   *0x200baa(%rip)        # 601000 <_GLOBAL_OFFSET_TABLE_+0x18>
  400456:       68 00 00 00 00          pushq  $0x0
  40045b:       e9 e0 ff ff ff          jmpq   400440 <_init+0x20>

0000000000400460 <__gmon_start__@plt>:
  400460:       ff 25 a2 0b 20 00       jmpq   *0x200ba2(%rip)        # 601008 <_GLOBAL_OFFSET_TABLE_+0x20>
  400466:       68 01 00 00 00          pushq  $0x1
  40046b:       e9 d0 ff ff ff          jmpq   400440 <_init+0x20>

0000000000400470 <rand@plt>:
  400470:       ff 25 9a 0b 20 00       jmpq   *0x200b9a(%rip)        # 601010 <_GLOBAL_OFFSET_TABLE_+0x28>
  400476:       68 02 00 00 00          pushq  $0x2
  40047b:       e9 c0 ff ff ff          jmpq   400440 <_init+0x20>

Disassembly of section .text:

0000000000400480 <main>:
  400480:       41 54                   push   %r12
  400482:       55                      push   %rbp
  400483:       31 ed                   xor    %ebp,%ebp
  400485:       53                      push   %rbx
  400486:       31 db                   xor    %ebx,%ebx
  400488:       0f 1f 84 00 00 00 00    nopl   0x0(%rax,%rax,1)
  40048f:       00 
  400490:       89 ef                   mov    %ebp,%edi
  400492:       e8 59 01 00 00          callq  4005f0 <divpow2re.constprop.0>
  400497:       89 ef                   mov    %ebp,%edi
  400499:       01 c3                   add    %eax,%ebx
  40049b:       83 c5 01                add    $0x1,%ebp
  40049e:       e8 6d 01 00 00          callq  400610 <divpow2re.constprop.1>
  4004a3:       01 c3                   add    %eax,%ebx
  4004a5:       83 fd 20                cmp    $0x20,%ebp
  4004a8:       75 e6                   jne    400490 <main+0x10>
  4004aa:       66 bd 00 04             mov    $0x400,%bp
  4004ae:       66 90                   xchg   %ax,%ax
  4004b0:       e8 bb ff ff ff          callq  400470 <rand@plt>
  4004b5:       41 89 c4                mov    %eax,%r12d
  4004b8:       41 c1 e4 10             shl    $0x10,%r12d
  4004bc:       e8 af ff ff ff          callq  400470 <rand@plt>
  4004c1:       0f b7 d0                movzwl %ax,%edx
  4004c4:       45 8d a4 14 00 00 00    lea    -0x80000000(%r12,%rdx,1),%r12d
  4004cb:       80 
  4004cc:       e8 9f ff ff ff          callq  400470 <rand@plt>
  4004d1:       83 e0 1f                and    $0x1f,%eax
  4004d4:       44 89 e7                mov    %r12d,%edi
  4004d7:       89 c6                   mov    %eax,%esi
  4004d9:       e8 62 01 00 00          callq  400640 <divpow2re>
  4004de:       01 c3                   add    %eax,%ebx
  4004e0:       83 ed 01                sub    $0x1,%ebp
  4004e3:       75 cb                   jne    4004b0 <main+0x30>
  4004e5:       89 d8                   mov    %ebx,%eax
  4004e7:       5b                      pop    %rbx
  4004e8:       5d                      pop    %rbp
  4004e9:       41 5c                   pop    %r12
  4004eb:       c3                      retq   

00000000004004ec <_start>:
  4004ec:       31 ed                   xor    %ebp,%ebp
  4004ee:       49 89 d1                mov    %rdx,%r9
  4004f1:       5e                      pop    %rsi
  4004f2:       48 89 e2                mov    %rsp,%rdx
  4004f5:       48 83 e4 f0             and    $0xfffffffffffffff0,%rsp
  4004f9:       50                      push   %rax
  4004fa:       54                      push   %rsp
  4004fb:       49 c7 c0 d0 06 40 00    mov    $0x4006d0,%r8
  400502:       48 c7 c1 70 06 40 00    mov    $0x400670,%rcx
  400509:       48 c7 c7 80 04 40 00    mov    $0x400480,%rdi
  400510:       e8 3b ff ff ff          callq  400450 <__libc_start_main@plt>
  400515:       f4                      hlt    
  400516:       90                      nop
  400517:       90                      nop
  400518:       90                      nop
  400519:       90                      nop
  40051a:       90                      nop
  40051b:       90                      nop
  40051c:       90                      nop
  40051d:       90                      nop
  40051e:       90                      nop
  40051f:       90                      nop
  400520:       b8 2f 10 60 00          mov    $0x60102f,%eax
  400525:       55                      push   %rbp
  400526:       48 2d 28 10 60 00       sub    $0x601028,%rax
  40052c:       48 89 e5                mov    %rsp,%rbp
  40052f:       48 83 f8 0e             cmp    $0xe,%rax
  400533:       76 1b                   jbe    400550 <_start+0x64>
  400535:       b8 00 00 00 00          mov    $0x0,%eax
  40053a:       48 85 c0                test   %rax,%rax
  40053d:       74 11                   je     400550 <_start+0x64>
  40053f:       bf 28 10 60 00          mov    $0x601028,%edi
  400544:       5d                      pop    %rbp
  400545:       ff e0                   jmpq   *%rax
  400547:       66 0f 1f 84 00 00 00    nopw   0x0(%rax,%rax,1)
  40054e:       00 00 
  400550:       5d                      pop    %rbp
  400551:       c3                      retq   
  400552:       66 66 66 66 66 2e 0f    data32 data32 data32 data32 nopw %cs:0x0(%rax,%rax,1)
  400559:       1f 84 00 00 00 00 00 
  400560:       be 28 10 60 00          mov    $0x601028,%esi
  400565:       55                      push   %rbp
  400566:       48 81 ee 28 10 60 00    sub    $0x601028,%rsi
  40056d:       48 89 e5                mov    %rsp,%rbp
  400570:       48 c1 fe 03             sar    $0x3,%rsi
  400574:       48 89 f0                mov    %rsi,%rax
  400577:       48 c1 e8 3f             shr    $0x3f,%rax
  40057b:       48 01 c6                add    %rax,%rsi
  40057e:       48 d1 fe                sar    %rsi
  400581:       74 15                   je     400598 <_start+0xac>
  400583:       b8 00 00 00 00          mov    $0x0,%eax
  400588:       48 85 c0                test   %rax,%rax
  40058b:       74 0b                   je     400598 <_start+0xac>
  40058d:       bf 28 10 60 00          mov    $0x601028,%edi
  400592:       5d                      pop    %rbp
  400593:       ff e0                   jmpq   *%rax
  400595:       0f 1f 00                nopl   (%rax)
  400598:       5d                      pop    %rbp
  400599:       c3                      retq   
  40059a:       66 0f 1f 44 00 00       nopw   0x0(%rax,%rax,1)
  4005a0:       80 3d 81 0a 20 00 00    cmpb   $0x0,0x200a81(%rip)        # 601028 <__bss_start>
  4005a7:       75 11                   jne    4005ba <_start+0xce>
  4005a9:       55                      push   %rbp
  4005aa:       48 89 e5                mov    %rsp,%rbp
  4005ad:       e8 6e ff ff ff          callq  400520 <_start+0x34>
  4005b2:       5d                      pop    %rbp
  4005b3:       c6 05 6e 0a 20 00 01    movb   $0x1,0x200a6e(%rip)        # 601028 <__bss_start>
  4005ba:       c3                      retq   
  4005bb:       0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)
  4005c0:       bf f8 0d 60 00          mov    $0x600df8,%edi
  4005c5:       48 83 3f 00             cmpq   $0x0,(%rdi)
  4005c9:       75 05                   jne    4005d0 <_start+0xe4>
  4005cb:       eb 93                   jmp    400560 <_start+0x74>
  4005cd:       0f 1f 00                nopl   (%rax)
  4005d0:       b8 00 00 00 00          mov    $0x0,%eax
  4005d5:       48 85 c0                test   %rax,%rax
  4005d8:       74 f1                   je     4005cb <_start+0xdf>
  4005da:       55                      push   %rbp
  4005db:       48 89 e5                mov    %rsp,%rbp
  4005de:       ff d0                   callq  *%rax
  4005e0:       5d                      pop    %rbp
  4005e1:       e9 7a ff ff ff          jmpq   400560 <_start+0x74>
  4005e6:       90                      nop
  4005e7:       90                      nop
  4005e8:       90                      nop
  4005e9:       90                      nop
  4005ea:       90                      nop
  4005eb:       90                      nop
  4005ec:       90                      nop
  4005ed:       90                      nop
  4005ee:       90                      nop
  4005ef:       90                      nop

00000000004005f0 <divpow2re.constprop.0>:
  4005f0:       85 ff                   test   %edi,%edi
  4005f2:       b8 ff ff ff 7f          mov    $0x7fffffff,%eax
  4005f7:       74 15                   je     40060e <divpow2re.constprop.0+0x1e>
  4005f9:       89 f9                   mov    %edi,%ecx
  4005fb:       b8 01 00 00 00          mov    $0x1,%eax
  400600:       d3 e0                   shl    %cl,%eax
  400602:       83 e8 01                sub    $0x1,%eax
  400605:       d1 f8                   sar    %eax
  400607:       05 ff ff ff 7f          add    $0x7fffffff,%eax
  40060c:       d3 f8                   sar    %cl,%eax
  40060e:       f3 c3                   repz retq 

0000000000400610 <divpow2re.constprop.1>:
  400610:       85 ff                   test   %edi,%edi
  400612:       89 f9                   mov    %edi,%ecx
  400614:       b8 00 00 00 80          mov    $0x80000000,%eax
  400619:       74 1a                   je     400635 <divpow2re.constprop.1+0x25>
  40061b:       ba 01 00 00 00          mov    $0x1,%edx
  400620:       d3 f8                   sar    %cl,%eax
  400622:       d3 e2                   shl    %cl,%edx
  400624:       83 e0 01                and    $0x1,%eax
  400627:       83 ea 01                sub    $0x1,%edx
  40062a:       d1 fa                   sar    %edx
  40062c:       8d 84 10 00 00 00 80    lea    -0x80000000(%rax,%rdx,1),%eax
  400633:       d3 f8                   sar    %cl,%eax
  400635:       f3 c3                   repz retq 
  400637:       66 0f 1f 84 00 00 00    nopw   0x0(%rax,%rax,1)
  40063e:       00 00 

0000000000400640 <divpow2re>:
  400640:       85 f6                   test   %esi,%esi
  400642:       89 f1                   mov    %esi,%ecx
  400644:       89 f8                   mov    %edi,%eax
  400646:       74 17                   je     40065f <divpow2re+0x1f>
  400648:       d3 ff                   sar    %cl,%edi
  40064a:       83 e7 01                and    $0x1,%edi
  40064d:       01 c7                   add    %eax,%edi
  40064f:       b8 01 00 00 00          mov    $0x1,%eax
  400654:       d3 e0                   shl    %cl,%eax
  400656:       83 e8 01                sub    $0x1,%eax
  400659:       d1 f8                   sar    %eax
  40065b:       01 f8                   add    %edi,%eax
  40065d:       d3 f8                   sar    %cl,%eax
  40065f:       f3 c3                   repz retq 
  400661:       90                      nop
  400662:       90                      nop
  400663:       90                      nop
  400664:       90                      nop
  400665:       90                      nop
  400666:       90                      nop
  400667:       90                      nop
  400668:       90                      nop
  400669:       90                      nop
  40066a:       90                      nop
  40066b:       90                      nop
  40066c:       90                      nop
  40066d:       90                      nop
  40066e:       90                      nop
  40066f:       90                      nop

0000000000400670 <__libc_csu_init>:
  400670:       41 57                   push   %r15
  400672:       41 89 ff                mov    %edi,%r15d
  400675:       41 56                   push   %r14
  400677:       49 89 f6                mov    %rsi,%r14
  40067a:       41 55                   push   %r13
  40067c:       49 89 d5                mov    %rdx,%r13
  40067f:       41 54                   push   %r12
  400681:       4c 8d 25 60 07 20 00    lea    0x200760(%rip),%r12        # 600de8 <__init_array_start>
  400688:       55                      push   %rbp
  400689:       48 8d 2d 60 07 20 00    lea    0x200760(%rip),%rbp        # 600df0 <__init_array_end>
  400690:       53                      push   %rbx
  400691:       4c 29 e5                sub    %r12,%rbp
  400694:       31 db                   xor    %ebx,%ebx
  400696:       48 83 ec 08             sub    $0x8,%rsp
  40069a:       e8 81 fd ff ff          callq  400420 <_init>
  40069f:       48 c1 fd 03             sar    $0x3,%rbp
  4006a3:       74 19                   je     4006be <__libc_csu_init+0x4e>
  4006a5:       0f 1f 00                nopl   (%rax)
  4006a8:       4c 89 ea                mov    %r13,%rdx
  4006ab:       4c 89 f6                mov    %r14,%rsi
  4006ae:       44 89 ff                mov    %r15d,%edi
  4006b1:       41 ff 14 dc             callq  *(%r12,%rbx,8)
  4006b5:       48 83 c3 01             add    $0x1,%rbx
  4006b9:       48 39 eb                cmp    %rbp,%rbx
  4006bc:       75 ea                   jne    4006a8 <__libc_csu_init+0x38>
  4006be:       48 83 c4 08             add    $0x8,%rsp
  4006c2:       5b                      pop    %rbx
  4006c3:       5d                      pop    %rbp
  4006c4:       41 5c                   pop    %r12
  4006c6:       41 5d                   pop    %r13
  4006c8:       41 5e                   pop    %r14
  4006ca:       41 5f                   pop    %r15
  4006cc:       c3                      retq   
  4006cd:       0f 1f 00                nopl   (%rax)

00000000004006d0 <__libc_csu_fini>:
  4006d0:       c3                      retq   
  4006d1:       90                      nop
  4006d2:       90                      nop
  4006d3:       90                      nop

Disassembly of section .fini:

00000000004006d4 <_fini>:
  4006d4:       48 83 ec 08             sub    $0x8,%rsp
  4006d8:       48 83 c4 08             add    $0x8,%rsp
  4006dc:       c3                      retq

**Comment by bchurchill** [comment]
I think I have a fix ready.  It'll be a little while before I push it, but if you want to apply it yourself, go to `src/ext/x64asm/src/att.l`.  On line 108, it has,

```
"."[a-zA-Z0-9]+ { yylval.operand....
```

change it to


```
"."[a-zA-Z0-9.]+ { yylval.operand....
```
There's an extra '.' inside the regex capture group in the new version.  Then go to the root directory of the distribution, do make clean && make.

Another work-around is to turn off GCC's constant propogation.  That was the root cause.
May I have your permission to add the binary you sent us to our test suite?

**Comment by ainar-g** [comment]
@bchurchill If you extend it to `"."[a-zA-Z0-9_.(*)]+` it will also support most Go functions and methods, although I don't know whether you plan on supporting Go. If you do, I can file an issue collecting all the problems I've had so far trying to use stoke with Go binaries.

**Comment by bchurchill** [comment]
Please do document these issues.  We can't promise that we'll work on them, but we'll at least take a look and see what we can do.  Supporting Go would definitely be a plus for us, but it's currently not a priority internally.

Please keep in mind that within the next few weeks we're going to be making a big release with about a year's worth of development included, so it's _possible_ that some have been fixed.  Also, once the release comes out, feel free to make pull requests against it.

**Comment by ainar-g** [comment]
Filed #27.
