### ISSUE TITLE
Pin app terminated abnormally

### ISSUE THREAD

**Issue by zefyrr** [StanfordPL/stoke-release#21]
When I try to run the testcase generator I get this - 

pinbin: ../../../../../ext/cpputil/include/allocator/aligned.h:46: T* Aligned<T, N>::allocate(Aligned<T, N>::size_type, std::allocator<void>::const_pointer) [with T = long unsigned int; long unsigned int N = 32ul; Aligned<T, N>::pointer = long unsigned int*; Aligned<T, N>::size_type = long unsigned int; std::allocator<void>::const_pointer = const void*]: Assertion `res == 0' failed.
Pin app terminated abnormally due to signal 6.

**Comment by bchurchill** [comment]
We'll need a lot more context to reproduce this.  If you could zip all your files together along with steps to reproduce and send them to us, we can look when we get a chance.
